### ISSUE TITLE
Support github enterprise please

### ISSUE THREAD

**Issue by mekhanique** [jonasws/github-utils#2]
Could you enable an option here where the user might select from a check box to point at their own github enterprise instances API end point rather than github.com (or possibly support more than one instance such as github.com and one or more private github enterprise instances)?

Before you ask for a pull request, I'm not allowed to do so by my employer (so all I can do is file the issue :-/ )

**Comment by jonasws** [comment]
That is a great suggestion! I've never used GitHub Enterprise myself, so it has never crossed my mind to implement support for it.

**Comment by jonasws** [comment]
Closing this as I've added support for this in v0.10.0

**Comment by mekhanique** [comment]
Thanks!
